### PR TITLE
Feature/9 basic plot validation fix git history

### LINKED ISSUE #9: Basic Plot Validations
Asana task: https://app.asana.com/1/77063628301548/project/1204166279674278/task/1212995413465054?focus=true

## TODO/DONE

- [x] Use JTS Topology Suite (org.locationtech.jts:jts-core) to handle geometry validation (equivalent to Python's shapely).
- [x] The app MUST accept the polygon data via the Intent Extras (specifically the value string passed from the ODK form field).
- [x] The app MUST parse the incoming string into a JTS Polygon object.
- [x] Geometry Validation Logic:
- [x] Vertex Count (Too Few Vertices)
- [x] Minimum Area (Polygon Too Small)
- [x] Topology (Self-Intersecting Lines)
- [x] Display an AlertDialog that cannot be dismissed by clicking outside the box (Force Cancellation).

### PR DESCRIPTION
**Pull request by ifirmawan**
### Overview
Implements basic polygon validation as an ODK external app using JTS Topology Suite. This allows ODK Collect forms to validate geoshape data before submission, ensuring data quality by checking for common geometry errors.

---

### 1. **Polygon Validation Logic**
- **PolygonValidator** class with three validation checks:
  - **Vertex Count**: Polygon must have at least 3 distinct points (4 including closing point)
  - **Minimum Area**: Polygon must be larger than 10 square meters (configurable)
  - **Self-Intersection**: Polygon edges cannot cross each other

### 2. **ODK External App Integration**
- **PolygonValidationActivity**: Android activity that integrates with ODK Collect
- Intent filter: `com.akvo.externalodk.VALIDATE_POLYGON`
- Input parameter: `shape` (geoshape data from XLSForm)
- Returns `RESULT_OK` on success, `RESULT_CANCELED` on failure

### 3. **Supported Input Formats**
- **ODK Geoshape**: `lat lng alt acc; lat lng alt acc; ...` (semicolon-separated points)
- **WKT**: `POLYGON ((x1 y1, x2 y2, x3 y3, x1 y1))`

### 4. **Error Handling**
- AlertDialog displays validation errors to the user
- Blocks form progression until polygon is corrected
- User-friendly error messages for each validation failure

---

## Dependencies Added

```toml
jts = "1.19.0"           # JTS Topology Suite for geometry operations
androidx-appcompat       # AppCompat for AlertDialog theming
```

---

## Files Changed

| File | Change | Description |
|------|--------|-------------|
| `PolygonValidator.kt` | Added | Core validation logic with JTS (122 lines) |
| `PolygonValidationActivity.kt` | Added | ODK external app activity (55 lines) |
| `PolygonValidatorTest.kt` | Added | 12 unit tests covering all scenarios (168 lines) |
| `AndroidManifest.xml` | Modified | Added activity with intent filter |
| `themes.xml` | Modified | Added AppCompat theme |
| `build.gradle.kts` | Modified | Added JTS and AppCompat dependencies |
| `libs.versions.toml` | Modified | Added JTS version catalog entry |
| `README.md` | Modified | Added ODK external app documentation |

**Statistics**: 9 files changed, +448 additions

---

## XLSForm Configuration

```
| type     | name             | label           | appearance                                                        | required |
|----------|------------------|-----------------|-------------------------------------------------------------------|----------|
| geoshape | manual_boundary  | Draw boundary   |                                                                   | yes      |
| text     | validate_trigger | Tap to validate | ex:com.akvo.externalodk.VALIDATE_POLYGON(shape=${manual_boundary}) |yes      |
```

---

## How Blocking Works

1. **Validation fails**: App returns `RESULT_CANCELED` and shows an error AlertDialog. ODK Collect does NOT update the field value - user must fix the polygon.

2. **Validation passes**: App returns `RESULT_OK` with the data. ODK Collect accepts the value and allows the user to proceed.

---

### Unit Tests (12 tests)
- [x] Valid large polygon passes all checks
- [x] Polygon with too few vertices fails
- [x] Polygon with area too small fails
- [x] Self-intersecting (bowtie) polygon fails
- [x] Valid WKT polygon passes validation
- [x] Invalid WKT format fails
- [x] Empty string fails validation
- [x] Whitespace only string fails validation
- [x] ODK format without altitude/accuracy parses correctly
- [x] Custom minimum area threshold works
- [x] Custom minimum vertices threshold works
- [x] Line with 3 points validation

### Manual Testing
- [ ] Valid polygon passes validation in ODK Collect
- [ ] Small polygon shows error dialog
- [ ] Self-intersecting polygon shows error dialog
- [ ] Too few vertices shows error dialog
- [ ] Integration test with actual Kobo form

---

## Installation

1. Build the APK: `./gradlew assembleDebug`
2. Install on the same device as ODK Collect: `./gradlew installDebug`
3. Configure your XLSForm with the external app appearance
4. Deploy the form to your device

---

## Related Issues

- Closes #9 - Basic Plot Validations

---

## Checklist

- [x] JTS Topology Suite dependency added
- [x] PolygonValidator with vertex, area, and intersection checks
- [x] PolygonValidationActivity with ODK intent handling
- [x] AppCompat theme for AlertDialog
- [x] Error AlertDialog UI
- [x] Unit tests for all validation scenarios
- [x] README documentation updated

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1212995413465054

### CODE REVIEW

File: app/src/main/java/org/akvo/afribamodkvalidator/validation/PolygonValidator.kt [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+     * Each point is space-separated: latitude longitude altitude accuracy
+     * Points are separated by semicolons
+     */
+    private fun parseOdkGeoshape(input: String): Polygon? {
+        return try {
+            val points = input.trim().split(";")
+                .map { it.trim() }
+                .filter { it.isNotEmpty() }
+                .map { pointStr ->
+                    val parts = pointStr.split("\\s+".toRegex())
```
Comment (zuhdil) [inline app/src/main/java/org/akvo/afribamodkvalidator/validation/PolygonValidator.kt]: Creating a new regex on each iteration is inefficient. Extract to a companion object

```kotlin
companion object {
  private val WHITESPACE_REGEX = "\\s+".toRegex()
  // ...
}
```

**Review by zuhdil — CHANGES_REQUESTED** [review]
